os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "4.4.2"
jdk:
  - oraclejdk8
env:
  global:
  - JHIPSTER_NODE_CACHE=1
  - PROFILE=dev
  - RUN_APP=1
  - PROTRACTOR=0
  - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
  - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
  - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
  - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
  matrix:
  - JHIPSTER=app-default-from-scratch JHIPSTER_NODE_CACHE=0
  - JHIPSTER=app-gradle
install:
  - $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
  - $JHIPSTER_INSTALL/03-checkVersion.sh
  - $JHIPSTER_INSTALL/04-cache.sh
script:
  - $JHIPSTER_SCRIPTS/01-generate-project.sh
  - $JHIPSTER_SCRIPTS/02-generate-entities.sh
  - $JHIPSTER_SCRIPTS/04-tests.sh
  - $JHIPSTER_SCRIPTS/05-test-leaflet.sh
